import { Header } from '../components/Header/Header'
import './global.css'

export const metadata = {
  title: 'Welcome to next-app',
  description: 'Generated by create-nx-workspace',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div className="container">
          <Header />
          {children}
        </div>
      </body>
    </html>
  )
}
