import './global.css'
import { ClerkProvider } from '@clerk/nextjs'

export const metadata = {
  title: 'Welcome to next-mood',
  description: 'Generated by create-nx-workspace',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <head>
          <title>Hello</title>
        </head>

        <body>{children}</body>
      </html>
    </ClerkProvider>
  )
}
