import './global.css'

export const metadata = {
  title: 'Welcome to next-mood',
  description: 'Generated by create-nx-workspace',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <title>Hello</title>
      </head>

      <body>{children}</body>
    </html>
  )
}
