import './global.css'
import { ClerkProvider } from '@clerk/nextjs'

export const metadata = {
  title: 'Welcome to next-mood',
  description: 'Generated by create-nx-workspace',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <ClerkProvider>{children}</ClerkProvider>
      </body>
    </html>
  )
}
