name: Deploy to GitHub Page from main branch
on:
  push:
    branches:
      - main
jobs:
  run-test-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [20.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: |
          yarn install
      - name: Build
        run: |
          yarn nx build-ci learn-german
          pwd
      # - name: Deploy to Github page
      #   uses: JamesIves/github-pages-deploy-action@3.7.1
      #   with:
      #     ACCESS_TOKEN: ${{ secrets.LERAN_GERMAN_DEPLOY_TEST  }}
      #     BRANCH: master # The branch the action should deploy to.
      #     FOLDER: dist/apps/learn-german # The folder the action should deploy.
      #     REPOSITORY_NAME: takahirohonda/takahirohonda.github.io
      #     TARGET_FOLDER: learn-german
      #     CLEAN: true # Automatically remove deleted files from the deploy branch
